const mockData = [
  {
    id: 1,
    name: "Jan",
    position: "VP Accounting",
    office: "Yahil’nytsya",
    age: 86,
    startDate: "30/03/2020",
  },
  {
    id: 2,
    name: "Webster",
    position: "Developer IV",
    office: "Yakymivka",
    age: 72,
    startDate: "11/12/2019",
  },
  {
    id: 3,
    name: "Antons",
    position: "Developer II",
    office: "Kax",
    age: 52,
    startDate: "06/04/2019",
  },
  {
    id: 4,
    name: "Deck",
    position: "Accountant III",
    office: "Montelíbano",
    age: 69,
    startDate: "07/10/2020",
  },
  {
    id: 5,
    name: "Stephannie",
    position: "Biostatistician II",
    office: "Lasi Dua",
    age: 40,
    startDate: "21/10/2020",
  },
  {
    id: 6,
    name: "Antons",
    position: "Compensation Analyst",
    office: "Mariposa",
    age: 57,
    startDate: "29/12/2019",
  },
  {
    id: 7,
    name: "Ferrel",
    position: "Food Chemist",
    office: "Valle Grande",
    age: 94,
    startDate: "19/07/2019",
  },
  {
    id: 8,
    name: "Lorrie",
    position: "Environmental Specialist",
    office: "Barabedang",
    age: 86,
    startDate: "24/07/2020",
  },
  {
    id: 9,
    name: "Edgar",
    position: "Systems Administrator III",
    office: "Waxi",
    age: 33,
    startDate: "04/10/2020",
  },
  {
    id: 10,
    name: "Leroy",
    position: "Analog Circuit Design manager",
    office: "Paciran",
    age: 48,
    startDate: "31/05/2020",
  },
  {
    id: 11,
    name: "Gayleen",
    position: "Senior Financial Analyst",
    office: "Santa Cruz",
    age: 24,
    startDate: "25/03/2021",
  },
  {
    id: 12,
    name: "Laurence",
    position: "Accountant I",
    office: "Vessada",
    age: 81,
    startDate: "10/04/2020",
  },
  {
    id: 13,
    name: "Barri",
    position: "Biostatistician II",
    office: "Sivers’k",
    age: 89,
    startDate: "20/07/2020",
  },
  {
    id: 14,
    name: "Meir",
    position: "Project Manager",
    office: "Nekrasovka",
    age: 22,
    startDate: "16/12/2019",
  },
  {
    id: 15,
    name: "Gerri",
    position: "Staff Scientist",
    office: "Manadhoo",
    age: 95,
    startDate: "21/10/2019",
  },
  {
    id: 16,
    name: "Cecilius",
    position: "Social Worker",
    office: "Penisihan",
    age: 41,
    startDate: "29/01/2021",
  },
  {
    id: 17,
    name: "Angela",
    position: "Desktop Support Technician",
    office: "Vlorë",
    age: 81,
    startDate: "03/12/2019",
  },
  {
    id: 18,
    name: "Jefferey",
    position: "Teacher",
    office: "Mubi",
    age: 53,
    startDate: "25/06/2020",
  },
  {
    id: 19,
    name: "Kacie",
    position: "Engineer IV",
    office: "Hongsung",
    age: 34,
    startDate: "30/06/2020",
  },
  {
    id: 20,
    name: "Lodovico",
    position: "Safety Technician III",
    office: "Viale",
    age: 87,
    startDate: "07/10/2020",
  },
  {
    id: 21,
    name: "Adah",
    position: "Social Worker",
    office: "Lyon",
    age: 61,
    startDate: "22/12/2019",
  },
  {
    id: 22,
    name: "Katusha",
    position: "Software Test Engineer I",
    office: "Mymensingh",
    age: 65,
    startDate: "16/01/2020",
  },
  {
    id: 23,
    name: "Brandy",
    position: "Biostatistician III",
    office: "Tabia",
    age: 64,
    startDate: "11/03/2021",
  },
  {
    id: 24,
    name: "Bathsheba",
    position: "Director of Sales",
    office: "Tartouss",
    age: 65,
    startDate: "27/06/2020",
  },
  {
    id: 25,
    name: "Giorgia",
    position: "Project Manager",
    office: "Hanjia",
    age: 93,
    startDate: "22/09/2020",
  },
  {
    id: 26,
    name: "Gavan",
    position: "Staff Accountant III",
    office: "Jangkat",
    age: 70,
    startDate: "15/12/2019",
  },
  {
    id: 27,
    name: "Adelind",
    position: "Assistant Manager",
    office: "Bawshar",
    age: 77,
    startDate: "06/05/2020",
  },
  {
    id: 28,
    name: "Normand",
    position: "Quality Control Specialist",
    office: "Tuchlovice",
    age: 41,
    startDate: "14/09/2019",
  },
  {
    id: 29,
    name: "Odilia",
    position: "Product Engineer",
    office: "Bitanjuan",
    age: 94,
    startDate: "29/11/2020",
  },
  {
    id: 30,
    name: "Sylvester",
    position: "Chemical Engineer",
    office: "Veliko Tŭrnovo",
    age: 72,
    startDate: "22/04/2019",
  },
  {
    id: 31,
    name: "Melantha",
    position: "VP Quality Control",
    office: "Boston",
    age: 51,
    startDate: "08/02/2021",
  },
  {
    id: 32,
    name: "Wynn",
    position: "Civil Engineer",
    office: "Ershilipu",
    age: 58,
    startDate: "29/08/2019",
  },
  {
    id: 33,
    name: "Novelia",
    position: "Chemical Engineer",
    office: "Budaka",
    age: 79,
    startDate: "22/06/2019",
  },
  {
    id: 34,
    name: "Tamarra",
    position: "Senior Quality Engineer",
    office: "Roma",
    age: 93,
    startDate: "21/03/2020",
  },
  {
    id: 35,
    name: "Emilio",
    position: "Computer Systems Analyst II",
    office: "Indaial",
    age: 81,
    startDate: "04/09/2020",
  },
  {
    id: 36,
    name: "Enid",
    position: "Environmental Tech",
    office: "Castelo",
    age: 37,
    startDate: "03/09/2019",
  },
  {
    id: 37,
    name: "Mic",
    position: "Product Engineer",
    office: "Weiyanggong",
    age: 40,
    startDate: "20/02/2020",
  },
  {
    id: 38,
    name: "Mara",
    position: "Paralegal",
    office: "Zhengwan",
    age: 74,
    startDate: "24/07/2020",
  },
  {
    id: 39,
    name: "Stormie",
    position: "Structural Analysis Engineer",
    office: "Valerik",
    age: 69,
    startDate: "24/06/2020",
  },
  {
    id: 40,
    name: "Bil",
    position: "Senior Editor",
    office: "Ganjun",
    age: 77,
    startDate: "21/12/2019",
  },
  {
    id: 41,
    name: "Estella",
    position: "Administrative Officer",
    office: "Detupia",
    age: 44,
    startDate: "14/02/2021",
  },
  {
    id: 42,
    name: "Suzanna",
    position: "Web Developer I",
    office: "Pankrushikha",
    age: 21,
    startDate: "22/01/2021",
  },
  {
    id: 43,
    name: "Zane",
    position: "Environmental Tech",
    office: "Ziębice",
    age: 58,
    startDate: "01/05/2019",
  },
  {
    id: 44,
    name: "Cherlyn",
    position: "Data Coordiator",
    office: "Železná Ruda",
    age: 77,
    startDate: "09/11/2019",
  },
  {
    id: 45,
    name: "Agretha",
    position: "Programmer IV",
    office: "Alíartos",
    age: 36,
    startDate: "24/01/2021",
  },
  {
    id: 46,
    name: "Goldy",
    position: "Desktop Support Technician",
    office: "Xiaolin",
    age: 37,
    startDate: "12/08/2019",
  },
  {
    id: 47,
    name: "Raina",
    position: "Occupational Therapist",
    office: "Jiaokui",
    age: 65,
    startDate: "05/02/2021",
  },
  {
    id: 48,
    name: "Kaitlyn",
    position: "Chemical Engineer",
    office: "Santa Rosa de Aguán",
    age: 83,
    startDate: "26/02/2020",
  },
  {
    id: 49,
    name: "Abbey",
    position: "Associate Professor",
    office: "Casal da Anja",
    age: 54,
    startDate: "25/12/2020",
  },
  {
    id: 50,
    name: "Porter",
    position: "Information Systems Manager",
    office: "Monte de Trigo",
    age: 51,
    startDate: "04/07/2020",
  },
  {
    id: 51,
    name: "Colette",
    position: "GIS Technical Architect",
    office: "Blagoveshchensk",
    age: 92,
    startDate: "05/02/2021",
  },
  {
    id: 52,
    name: "Whitman",
    position: "Actuary",
    office: "Seremban",
    age: 54,
    startDate: "10/08/2019",
  },
  {
    id: 53,
    name: "Hasheem",
    position: "GIS Technical Architect",
    office: "Al Jumūm",
    age: 29,
    startDate: "19/04/2020",
  },
  {
    id: 54,
    name: "Norry",
    position: "Internal Auditor",
    office: "Åby",
    age: 59,
    startDate: "19/09/2020",
  },
  {
    id: 55,
    name: "Emmerich",
    position: "Community Outreach Specialist",
    office: "Wu’erbu Baolige",
    age: 74,
    startDate: "26/03/2021",
  },
  {
    id: 56,
    name: "Sorcha",
    position: "Compensation Analyst",
    office: "Yao’an",
    age: 97,
    startDate: "02/05/2019",
  },
  {
    id: 57,
    name: "Kirsti",
    position: "Nuclear Power Engineer",
    office: "Detik Satu",
    age: 52,
    startDate: "28/11/2020",
  },
];
